footer + card :D
wermote/wermote pull request #12
Opened 2021-12-08 02:30 UTC by tudulceprincesa18

2021-12-09 04:30 UTC, omarcresp requested changes

2021-12-09 04:30 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Card/index.tsx
> +        <div className={CardStyles .container}>
no deberia haber un espacio en blanco en este objeto
```CardStyles.container```

2021-12-09 04:30 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Footer/index.module.css
> +h1{
en un css module todo deberian ser clases

2021-12-10 15:47 UTC, tudulceprincesa18 commented on apps/jackbnb-fe/src/components/Card/index.tsx
> +        <div className={CardStyles .container}>
literalmente hice lo que me dijiste

2021-12-10 15:48 UTC, tudulceprincesa18 commented on apps/jackbnb-fe/src/components/Footer/index.module.css
> +h1{
pero si lo corregimos en la llamada

2022-01-08 22:46 UTC, omarcresp requested changes

2022-01-08 22:46 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Card/index.module.css
> +    -webkit-box-shadow: 10px 9px 103px 138px rgba(31,8,8,0.27) inset;
Los estilos con prefijos no se deberian poner

2022-01-08 22:46 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Card/index.module.css
> +.container{
```suggestion
.container {
```

2022-01-08 22:46 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Card/index.tsx
> +        <div className={CardStyles .container}>
```suggestion
        <div className={CardStyles.container}>
```

2022-01-08 22:46 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Footer/index.module.css
> +    font-family: 'cobin', 'sans serif';
```suggestion
    font-family: 'Cabin', 'sans serif';
```

2022-01-08 22:46 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Footer/index.module.css
> +@import url('https://fonts.googleapis.com/css2?family=Lexend+Deca&display=swap');
porfa borralos que las fuentes hay que añadirlas con `<link />` en el `<head/>`

2022-01-08 22:46 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Footer/index.tsx
> +import FooterStyles from './index.module.css';
Recorda el espacio entre los import de las librerias y los import de otros archivos
```suggestion
import React from 'react';

import Form from '../Form'
import FormButton from '../SecondaryButton';
import FooterStyles from './index.module.css';
```

2022-01-08 22:52 UTC, omarcresp requested changes

2022-01-08 22:52 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Form/index.tsx
> +  import MyTestButtonStyles from './index.module.css'
Corregir los espacios
```suggestion
} from "@chakra-ui/react"

import MyTestButtonStyles from './index.module.css'
```

2022-01-08 22:52 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Header/index.tsx
> +return(
falto identación

2022-01-08 22:52 UTC, omarcresp commented on apps/jackbnb-fe/src/components/Card/index.tsx
> +    return(
corregir identacion (2 espacios)

2022-01-13 04:09 UTC, omarcresp approved these changes

2022-01-20 02:21 UTC, merged